[package]
name = "rtodo"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
ratatui = "0.27.0"
time = { version = "0.3.36", features = ["formatting", "macros", "local-offset"] }
tui-input = "0.9.0"
